### PR TITLE
Added support for dead-letters, routing key, and message ttl

### PR DESCRIPTION
**Pull request by ghost**
I, let me start be congratulating you for this great tool.
I've added some changes to the configuration structure so that i could pass some arguments that i needed. I think it can be useful to other people using this tool .

Let me know what you think, cheers.

### CODE REVIEW

**Comment by ricbra** [comment]
Hi @filipemarinheiro 

First of all: thanks for your work!

It would be nice to get dead-letter exchange support in. The current implementation isn't backward compatible anymore because you moved `queue` to another section. If merged in, this will break existing installations. 

I propose the following:
1. move `queue` back to its original section;
2. keep the new options under the new `queue` section.

Could you also [go fmt](https://blog.golang.org/go-fmt-your-code) your code before commiting?

**Comment by ghost** [comment]
Hi.
I've made the changes you suggested, the Queue section was renamed to QueueSetting i think it is more suggestive of what is actually being configured.

Let me know what you think, cheers.

**Comment by ricbra** [comment]
Looks good, thanks again!

**Comment by sroze** [comment]
Sounds nice, I believe that helps to setup a delay queue. I've found [RabbitMq's article](https://www.rabbitmq.com/blog/2015/04/16/scheduling-messages-with-rabbitmq/) and this [PHP demo](https://github.com/php-amqplib/php-amqplib/blob/19a1753fc1d7ea5b1b1d0de732b551df54ce8a98/demo/delayed_message.php) but I can't get it configured by rabbitmq-cli-consumer. Any documentation or existing configuration to point me to?

**Pull request merged**
