### PR TITLE
Add delivery details to the JSON object

### PR DESCRIPTION
**Pull request by skolodyazhnyy**
I've added routing key to the properties array.

### CODE REVIEW

**Comment by skolodyazhnyy** [comment]
I've added `routing_key` to properties array, same as `redelivered`, although neither of those is valid property according to [AMQP Spec, section 1.8.1](https://www.rabbitmq.com/resources/specs/amqp-xml-doc0-9-1.pdf). So, may be it would be better to move both these options outside of the `properties` array, for example into `delivery_info` as in [php-amqplib](https://github.com/videlalvaro/php-amqplib/blob/master/PhpAmqpLib/Channel/AMQPChannel.php#L959).

**Comment by skolodyazhnyy** [comment]
Ok, I gave it some thinking and it seems logical to me to have all delivery details in the separate JSON property. Let me know what do you think.

**Comment by skolodyazhnyy** [comment]
/ping @ricbra

If you could find a moment to have a look into this PR and another one about exit codes would be great.

**Comment by ricbra** [comment]
Sorry for the delay @skolodyazhnyy 

This one looks good to me. Thanks again for your work!

**Pull request merged**
