### PR TITLE
Pass message properties and headers to the executed scripts

### PR DESCRIPTION
**Pull request by corvus-ch**
There are use cases where a consumer script needs access to properties and headers of an AMQP message. For that purpose, I have added a flag. If this flag is set, it will change the payload passed to the script. This alternate payload will be a JSON encoded data structure containing not only the body but also includes the messages properties and headers.

### CODE REVIEW

**Comment by ricbra** [comment]
Thanks for the PR. I'm AFK this week, so I'll respond next week.

Op ma 25 jan. 2016 08:40 schreef Christian Häusler <notifications@github.com

**Comment by ricbra** [comment]
Hi @corvus-ch ,

This looks good to me. Thanks for your contribution!

**Comment by skolodyazhnyy** [comment]
@ricbra Do you think would be possible to merge it (#23 and #24) into 2.0? Thanks in advance!

**Comment by ricbra** [comment]
Hi @skolodyazhnyy ,

Yes, it is definitely possible! The v2 version went a bit of my radar. Due to the fact I was quite busy and the lack of contributors to this project made me loss my motivation a bit. But last days PR make me a happy person, so I'm gonna invest some time to get v2 released as soon as possible.

**Pull request merged**
