### PR TITLE
Added build script for creating debian services

### PR DESCRIPTION
**Pull request by jskarpe**
Another approach for creating installable services for processing queues for easier integration with deployment tools such as Puppet

### CODE REVIEW

**Comment by ricbra** [comment]
Hi @Yuav,

Looks cool, I'm gonna give it a try asap!

**Comment by ricbra** [comment]
I've booted a fresh Debian Wheezy box, cloned your branch in <code>~/rabbitmq-cli-consumer</code> and then tried the script with all default values:

```
$ ./build_service_deb.sh
Name of service: rabbitmq-cli-consumer
Command to process queue item: /var/www/app/console -v acme:cmd 
Queue name: job_queue
cp: cannot stat `/home/vagrant/gocode/src/github.com/ricbra/rabbitmq-cli-consumer/rabbitmq-cli-consumer': No such file or directory
```

Could you look into this?

**Comment by jskarpe** [comment]
I believe this should be fixed now in my latest commit.

**Comment by ricbra** [comment]
Yep, it works now. Could you add a note about the package name on Debian (gccgo) so that the docs apply to both Ubuntu and Debian?

Then it's good to merge :+1:

**Comment by jskarpe** [comment]
README updated

**Comment by ricbra** [comment]
Thanks @Yuav

**Pull request merged**
